student=[]
s1=int(input("enter the marks of s1:"))
student.append(s1)
s2=int(input("enter the marks of s2:"))
student.append(s2)
s3=int(input("enter the marks of s3:"))
student.append(s3)
s4=int(input("enter the marks of s4:"))
student.append(s4)
s5=int(input("enter the marks of s5:"))
student.append(s5)
s6=int(input("enter the marks of s6:"))
student.append(s6)
print(student)
student.sort()
print(student)